<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-05-08">

<title>EIP Operations Website - Neria Brempong</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">EIP Operations Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./main.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#encounter-information" id="toc-encounter-information" class="nav-link active" data-scroll-target="#encounter-information">Encounter Information</a>
  <ul class="collapse">
  <li><a href="#assessments" id="toc-assessments" class="nav-link" data-scroll-target="#assessments">Assessments</a>
  <ul class="collapse">
  <li><a href="#substance-use-disorder-sud" id="toc-substance-use-disorder-sud" class="nav-link" data-scroll-target="#substance-use-disorder-sud">Substance Use Disorder (SUD)</a></li>
  <li><a href="#mental-health-mh" id="toc-mental-health-mh" class="nav-link" data-scroll-target="#mental-health-mh">Mental Health (MH)</a></li>
  <li><a href="#pre-exposure-prophylaxis-prep" id="toc-pre-exposure-prophylaxis-prep" class="nav-link" data-scroll-target="#pre-exposure-prophylaxis-prep">Pre-Exposure Prophylaxis (PrEP)</a></li>
  </ul></li>
  <li><a href="#hiv-testing" id="toc-hiv-testing" class="nav-link" data-scroll-target="#hiv-testing">HIV Testing</a></li>
  <li><a href="#hepatitis-c-testing" id="toc-hepatitis-c-testing" class="nav-link" data-scroll-target="#hepatitis-c-testing">Hepatitis C Testing</a></li>
  <li><a href="#referrals" id="toc-referrals" class="nav-link" data-scroll-target="#referrals">Referrals</a></li>
  <li><a href="#linkage-to-care" id="toc-linkage-to-care" class="nav-link" data-scroll-target="#linkage-to-care">Linkage to Care</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">



<div class="quarto-about-solana column-body">
  <div class="about-entity">
    <div class="entity-contents">
      <header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Neria Brempong</h1>
</div>
<div class="quarto-title-meta">
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 8, 2024</p>
    </div>
  </div>
  </div>
</header> 
      <div class="about-contents"><div id="hero-heading">
<p>This metrics report shows data for encounter information for <strong>Neria Brempong</strong>. Any data contained within this report covers clinical information captured in the EIP Database since <strong>January 1st, 2023</strong>. The metrics in this report describe specific encounter information and the services and/or referrals that were provided to patients/clients.</p>
<p>Until a unique patient identifier is created for patients seen by EIP, matching unique patients across multiple years of encounters is difficult. Therefore, patient demographic and population information will refer only to the number of encounters, not the unique number of patients. This part of the report is still in development.</p>
</div></div>
    </div>
    <img src="images/n_brempong.jpg" class="about-image
  rounded " style="width: 20em;">
  </div>
</div>

<section id="encounter-information" class="level1">
<h1>Encounter Information</h1>
<p>The remainder of this metrics report is all encounter-based information. Since some of our staff have responsibilities that may have them performing tasks that cross multiple roles within the program, all metrics are considered here when discussing encounter information. For example, linkage information is evaluated below even though not all staff perform linkage duties. This will keep the metric reports for all staff consistent, and allow for the transition into other roles at any time without an interruption in this reporting structure. Encounters are defined and stratified by EIP team member by the following information captured in the EIP Database:</p>
<ul>
<li><p><strong>Encounters:</strong> <em>An encounter is any visit that is created within the patient record in the EIP Database, whether service information is provided or not. Every encounter should have some type of service entered (i.e.&nbsp;Assessment, HIV/HCV Testing, Linkage), but is still counted as an encounter if something is entered within the record (i.e.&nbsp;just Encounter Information or Encounter Checklist info).</em></p></li>
<li><p><strong>Staff indication:</strong> <em>There are background variables on each page in the EIP Database that captures the REDCap username of the individual completing the form. If you created any of the forms for that encounter within the EIP Database, or if your name is selected as the “EIP Counselor” on the Encounter Checklist page, then you are attached to that record in some capacity and noted in these numbers. If you work as a peer and your name is selected on the “Peer Support” form, that also indicates that encounter as one you were involved with in some way, and thus counted here.</em></p></li>
</ul>
<p>Neria has had a total of <strong>245 encounters</strong> entered into the EIP Database since January 1st, 2023. A summary table of these encounters and what they consisted of are shown below.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">

<table data-quarto-disable-processing="true" class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto; font-size: 11px; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Date </th>
   <th style="text-align:center;"> Encounters </th>
   <th style="text-align:center;"> Assessments </th>
   <th style="text-align:center;"> % Assessed </th>
   <th style="text-align:center;"> CTR Tests </th>
   <th style="text-align:center;"> % CTR </th>
   <th style="text-align:center;"> EHE Tests </th>
   <th style="text-align:center;"> % EHE </th>
   <th style="text-align:center;"> HCV Tests </th>
   <th style="text-align:center;"> % HCV Tests </th>
   <th style="text-align:center;"> LTC Cases </th>
   <th style="text-align:center;"> % LTC Cases </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 01/2023 </td>
   <td style="text-align:center;"> 18 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 44.4% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 38.9% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 27.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 02/2023 </td>
   <td style="text-align:center;"> 16 </td>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 62.5% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 62.5% </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 25.0% </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 37.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 03/2023 </td>
   <td style="text-align:center;"> 31 </td>
   <td style="text-align:center;"> 19 </td>
   <td style="text-align:center;"> 61.3% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 15 </td>
   <td style="text-align:center;"> 48.4% </td>
   <td style="text-align:center;"> 12 </td>
   <td style="text-align:center;"> 38.7% </td>
   <td style="text-align:center;"> 12 </td>
   <td style="text-align:center;"> 38.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 04/2023 </td>
   <td style="text-align:center;"> 28 </td>
   <td style="text-align:center;"> 17 </td>
   <td style="text-align:center;"> 60.7% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 15 </td>
   <td style="text-align:center;"> 53.6% </td>
   <td style="text-align:center;"> 13 </td>
   <td style="text-align:center;"> 46.4% </td>
   <td style="text-align:center;"> 11 </td>
   <td style="text-align:center;"> 39.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 05/2023 </td>
   <td style="text-align:center;"> 11 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 27.3% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 9.1% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 9.1% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 9.1% </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 72.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 06/2023 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 50.0% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 25.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 25.0% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 25.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 07/2023 </td>
   <td style="text-align:center;"> 9 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 11.1% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 11.1% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 44.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 08/2023 </td>
   <td style="text-align:center;"> 12 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 41.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 09/2023 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 42.9% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 14.3% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 28.6% </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 57.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10/2023 </td>
   <td style="text-align:center;"> 17 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 29.4% </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 11.8% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 47.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 11/2023 </td>
   <td style="text-align:center;"> 19 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 42.1% </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 36.8% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 5.3% </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 42.1% </td>
   <td style="text-align:center;"> 11 </td>
   <td style="text-align:center;"> 57.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 12/2023 </td>
   <td style="text-align:center;"> 16 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 15 </td>
   <td style="text-align:center;"> 93.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 01/2024 </td>
   <td style="text-align:center;"> 12 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 8.3% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 8.3% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 83.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 02/2024 </td>
   <td style="text-align:center;"> 15 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 15 </td>
   <td style="text-align:center;"> 100.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 03/2024 </td>
   <td style="text-align:center;"> 21 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 9.5% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 4.8% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 4.8% </td>
   <td style="text-align:center;"> 16 </td>
   <td style="text-align:center;"> 76.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 04/2024 </td>
   <td style="text-align:center;"> 9 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 11.1% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 88.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;background-color: lightgrey !important;"> Totals </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 245 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 80 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 96.4% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 15 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 6.1% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 49 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 20.00% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 42 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 17.1% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 139 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 56.7% </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><br></p>
<p>The graph below shows the total number of encounters Neria has had during each month within the reporting period. Also, the total number of each service provided are shown by the trend lines, which allows you to see trends over time. The definitions for how each of these numbers are stratified is described below the graph. This plot is dynamic, meaning you can select and deselect each particular metric by clicking the text in the legend on the right to focus on particular services provided. The plot also has the ability to zoom in on particular time frames by dragging the pointer to select the desired timeframe, and you can also scroll through timepoints using the slider below the x-axis. You can reset the graph by double-clicking within the plot. As mentioned above, not all staff offer or perform these services, so you can deselect the ones not within Neria’s role for a more tailored focus of tasks. This is a visual representation of the data shown in the complete summary metrics table above.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-00c21bea5bbc5d2b7157" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-00c21bea5bbc5d2b7157">{"x":{"visdat":{"3cecde82a91":["function () ","plotlyVisDat"]},"cur_data":"3cecde82a91","attrs":{"3cecde82a91":{"x":{},"y":{},"marker":{"color":"black"},"name":"Encounters","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"},"3cecde82a91.1":{"x":{},"y":{},"marker":{"color":"lightcoral"},"name":"Assessments","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","mode":"lines+markers","line":{"color":"lightcoral"},"inherit":true},"3cecde82a91.2":{"x":{},"y":{},"marker":{"color":"lightskyblue"},"name":"CTR Tests","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","mode":"lines+markers","line":{"color":"lightskyblue"},"inherit":true},"3cecde82a91.3":{"x":{},"y":{},"marker":{"color":"darkgreen"},"name":"EHE Tests","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","mode":"lines+markers","line":{"color":"darkgreen"},"inherit":true},"3cecde82a91.4":{"x":{},"y":{},"marker":{"color":"gold"},"name":"HCV Tests","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","mode":"lines+markers","line":{"color":"gold"},"inherit":true},"3cecde82a91.5":{"x":{},"y":{},"marker":{"color":"#AB82FF"},"name":"LTC Cases","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","mode":"lines+markers","line":{"color":"#AB82FF"},"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Brempong Monthly Encounters & Services","yaxis":{"domain":[0,1],"automargin":true,"title":"Total"},"xaxis":{"domain":[0,1],"automargin":true,"title":"Date"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false,"displayModeBar":false},"data":[{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[18,16,31,28,11,4,9,12,7,17,19,16,12,15,21,9],"marker":{"color":"black","line":{"color":"rgba(31,119,180,1)"}},"name":"Encounters","type":"bar","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[8,10,19,17,3,2,1,0,3,5,8,0,1,0,2,1],"marker":{"color":"lightcoral","line":{"color":"rgba(255,127,14,1)"}},"name":"Assessments","type":"scatter","mode":"lines+markers","line":{"color":"lightcoral"},"error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[0,0,0,0,1,1,1,0,1,2,7,0,1,0,1,0],"marker":{"color":"lightskyblue","line":{"color":"rgba(44,160,44,1)"}},"name":"CTR Tests","type":"scatter","mode":"lines+markers","line":{"color":"lightskyblue"},"error_y":{"color":"rgba(44,160,44,1)"},"error_x":{"color":"rgba(44,160,44,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[7,10,15,15,1,0,0,0,0,0,1,0,0,0,0,0],"marker":{"color":"darkgreen","line":{"color":"rgba(214,39,40,1)"}},"name":"EHE Tests","type":"scatter","mode":"lines+markers","line":{"color":"darkgreen"},"error_y":{"color":"rgba(214,39,40,1)"},"error_x":{"color":"rgba(214,39,40,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[0,4,12,13,1,1,0,0,2,0,8,0,0,0,1,0],"marker":{"color":"gold","line":{"color":"rgba(148,103,189,1)"}},"name":"HCV Tests","type":"scatter","mode":"lines+markers","line":{"color":"gold"},"error_y":{"color":"rgba(148,103,189,1)"},"error_x":{"color":"rgba(148,103,189,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[5,6,12,11,8,1,4,5,4,8,11,15,10,15,16,8],"marker":{"color":"#AB82FF","line":{"color":"rgba(140,86,75,1)"}},"name":"LTC Cases","type":"scatter","mode":"lines+markers","line":{"color":"#AB82FF"},"error_y":{"color":"rgba(140,86,75,1)"},"error_x":{"color":"rgba(140,86,75,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<ul>
<li><p><strong>Assessments:</strong> <em>An Assessment is when at least one question located on the Risk Assessment form is answered during the encounter.</em></p></li>
<li><p><strong>CTR Tests:</strong> <em>A CTR test is a rapid-based HIV test collected via a fingerstick (or in extremely rare instances, an oral swab) that is not marked as an EHE test in the Reason for Offer Category on the HIV Testing form.</em></p></li>
<li><p><strong>EHE Tests:</strong> <em>An EHE test is a rapid-based HIV test collected via a fingerstick that is marked as an EHE test in the Reason for Offer Category on the HIV Testing form.</em></p></li>
<li><p><strong>HCV Tests:</strong> <em>A rapid-based HCV tested is counted when the sample type for the HCV test documented on the Testing - HCV form is a fingerstick test. Therefore, lab-based tests are not counted here.</em></p></li>
<li><p><strong>LTC Cases:</strong> <em>A Linkage to Care case is considered opened when one of the linkage services are selected on the start of the Linkage to Care form in the database. The number counted here are the total number of cases initiated during the encounter, not necessarily those open at that time (for example, a case still open from a prior month).</em></p></li>
</ul>
<section id="assessments" class="level2">
<h2 data-anchor-id="assessments">Assessments</h2>
<p>Assessment data contains a lot of important information regarding patient risk and needs, and help determine whether or not the appropriate information and referrals are being provided during the encounter. The assessment data is analyzed in this section and broken down by specific questions to determine when certain screening tools are utilized to determine patient needs. The assessment contains data regarding substance use disorder (<strong>SUD</strong>), mental health (<strong>MH</strong>), and pre-exposure prophylaxis (<strong>PrEP</strong>), all examined below. Neria has conducted a total of <strong>80 assessments</strong>, which means that 96.4% of Neria’s encounters consisted of an assessment (<em>80/245</em>).</p>
<p>A summary of the general monthly trends of screening for each of these conditions is shown in the plot below. The description of the screening tools, as well as the number of screens and positivity per month are discussed within this section as well.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-065f9e927767075d74d6" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-065f9e927767075d74d6">{"x":{"visdat":{"3cec772b6c2a":["function () ","plotlyVisDat"]},"cur_data":"3cec772b6c2a","attrs":{"3cec772b6c2a":{"x":{},"y":{},"marker":{"color":"lightcoral"},"name":"Assessments","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"},"3cec772b6c2a.1":{"x":{},"y":{},"marker":{"color":"#C1FFC1"},"name":"SUD Assessed","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","mode":"lines+markers","line":{"color":"#C1FFC1"},"inherit":true},"3cec772b6c2a.2":{"x":{},"y":{},"marker":{"color":"#AB82FF"},"name":"Brief MH Assessed","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","mode":"lines+markers","line":{"color":"#AB82FF"},"inherit":true},"3cec772b6c2a.3":{"x":{},"y":{},"marker":{"color":"#551A8B"},"name":"MH Assessed","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","mode":"lines+markers","line":{"color":"#551A8B"},"inherit":true},"3cec772b6c2a.4":{"x":{},"y":{},"marker":{"color":"olivedrab"},"name":"PrEP Eligible","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","mode":"lines+markers","line":{"color":"olivedrab"},"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Brempong Monthly Assessment Trends","yaxis":{"domain":[0,1],"automargin":true,"title":"Total"},"xaxis":{"domain":[0,1],"automargin":true,"title":"Date"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false,"displayModeBar":false},"data":[{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[8,10,19,17,3,2,1,0,3,5,8,0,1,0,2,1],"marker":{"color":"lightcoral","line":{"color":"rgba(31,119,180,1)"}},"name":"Assessments","type":"bar","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[8,10,19,17,3,1,1,0,3,5,8,0,1,0,1,1],"marker":{"color":"#C1FFC1","line":{"color":"rgba(255,127,14,1)"}},"name":"SUD Assessed","type":"scatter","mode":"lines+markers","line":{"color":"#C1FFC1"},"error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[3,0,3,0,0,0,0,0,0,3,0,0,0,0,0,0],"marker":{"color":"#AB82FF","line":{"color":"rgba(44,160,44,1)"}},"name":"Brief MH Assessed","type":"scatter","mode":"lines+markers","line":{"color":"#AB82FF"},"error_y":{"color":"rgba(44,160,44,1)"},"error_x":{"color":"rgba(44,160,44,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[3,0,3,0,0,0,0,0,0,3,0,0,0,0,0,0],"marker":{"color":"#551A8B","line":{"color":"rgba(214,39,40,1)"}},"name":"MH Assessed","type":"scatter","mode":"lines+markers","line":{"color":"#551A8B"},"error_y":{"color":"rgba(214,39,40,1)"},"error_x":{"color":"rgba(214,39,40,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[5,7,14,9,5,0,1,4,2,2,3,5,3,4,6,1],"marker":{"color":"olivedrab","line":{"color":"rgba(148,103,189,1)"}},"name":"PrEP Eligible","type":"scatter","mode":"lines+markers","line":{"color":"olivedrab"},"error_y":{"color":"rgba(148,103,189,1)"},"error_x":{"color":"rgba(148,103,189,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<section id="substance-use-disorder-sud" class="level3">
<h3 data-anchor-id="substance-use-disorder-sud">Substance Use Disorder (SUD)</h3>
<p>SUD disorder measures include the Alcohol Use Disorders Identification Test (AUDIT-C) for alcohol abuse as well as the National Institute on Drug Abuse (NIDA) Modified Alcohol, Smoking, and Substance Involvement Screening Test (ASSIST), or the NM-ASSIST for all forms of substance abuse disorder. If any of the questions within this scale are answered by the patient during the encounter, then they are considered <strong>screened for SUD</strong>. There are scores associated with these measures, and those are calculated within the EIP Database in the background as data is entered. If the individual meets criteria on either the AUDIT-C or the NM-ASSIST, then they are <strong>considered positive for a SUD</strong>. The total number of assessments completed by Neria during this reporting period is <strong>80</strong>, with <strong>78 assessments</strong> having been screened for a SUD (<em>97.5%, 78/80</em>). For all assessments where the individual was screened for a SUD, there were a total of <strong>4</strong> that were positive for SUD (<em>5.1%, 4/78</em>).</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">

<table data-quarto-disable-processing="true" class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto; font-size: 11px; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Date </th>
   <th style="text-align:center;"> Assessments </th>
   <th style="text-align:center;"> SUD Assessed </th>
   <th style="text-align:center;"> % SUD Assessed </th>
   <th style="text-align:center;"> SUD + </th>
   <th style="text-align:center;"> % SUD + </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 01/2023 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 02/2023 </td>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 03/2023 </td>
   <td style="text-align:center;"> 19 </td>
   <td style="text-align:center;"> 19 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 10.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 04/2023 </td>
   <td style="text-align:center;"> 17 </td>
   <td style="text-align:center;"> 17 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 05/2023 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 06/2023 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 50.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 07/2023 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 08/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 09/2023 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10/2023 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 40.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 11/2023 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 12/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 01/2024 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 02/2024 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 03/2024 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 50.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 04/2024 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;background-color: lightgrey !important;"> Totals </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 80 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 78 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 97.5% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 4 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 5.1% </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><br></p>
</section>
<section id="mental-health-mh" class="level3">
<h3 data-anchor-id="mental-health-mh">Mental Health (MH)</h3>
<p>MH measures within the EIP assessment include the Patient Health Questionnaire (PHQ) for depression, the Generalized Anxiety Disorder (GAD) scale for anxiety, and the Post-Traumatic Stress Disorder CheckList (PCL) for Civilians (PCL-C) for PTSD. If any of the questions within these scales are answered by the patient during the encounter, then they are considered <strong>screened for MH</strong>. There are scores associated with these measures, and those are calculated within the EIP Database in the background as data is entered. If the individual meets criteria on any of these scales for these MH conditions, then they are <strong>considered positive for a MH condition</strong>. However, <span style="color: red;">it is important to note: prior to January 2024, we only conducted the full MH measures for those that were also positive for a SUD, not all those assessed</span>. Prior to 2024, we conducted shortened versions of the PHQ (PHQ2) and the GAD (GAD2) for all those assessed, but we had only asked the full versions and the PCL-C scale when they were determined positive for any SUD. The total number of assessments where at least one of the questions were asked on these condensed scales was <strong>9</strong> (<em>11.2%, 9/80</em>). The total number of assessments where the patient screened positive for a SUD <em>and</em> completed at least one of the questions on these MH measures was <strong>9</strong> (<em>11.2%, 9/4</em>). <em>Remember, the denominator used here is the number of assessments where the individual was SUD positive (n = 4), not all assessments (n = 80), since the full MH assessments were only available to those who had a SUD prior to 2024.</em></p>
<p>For all assessments where the individual was positive for a SUD and screened for MH, there were a total of <strong>1</strong> that were positive for at least one of the MH conditions screened for on the EIP assessment (<em>11.1%, 1/9</em>). In regards to the specific conditions that were assessed, those are provided below the table.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">

<table data-quarto-disable-processing="true" class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto; font-size: 11px; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Date </th>
   <th style="text-align:center;"> Assessments </th>
   <th style="text-align:center;"> Brief MH Assessed </th>
   <th style="text-align:center;"> % Brief MH Assessed </th>
   <th style="text-align:center;"> SUD + </th>
   <th style="text-align:center;"> MH Assessed </th>
   <th style="text-align:center;"> % MH Assessed </th>
   <th style="text-align:center;"> MH + </th>
   <th style="text-align:center;"> % MH + </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 01/2023 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 37.5% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> Inf </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 02/2023 </td>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 03/2023 </td>
   <td style="text-align:center;"> 19 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 15.8% </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 150.0% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 33.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 04/2023 </td>
   <td style="text-align:center;"> 17 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 05/2023 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 06/2023 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 07/2023 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 08/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 09/2023 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10/2023 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 60.0% </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 150.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 11/2023 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 12/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 01/2024 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 02/2024 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 03/2024 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 04/2024 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;background-color: lightgrey !important;"> Totals </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 80 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 9 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 11.2% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 4 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 9 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 11.2% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 1 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 11.1% </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><br></p>
<ul>
<li><p><strong>Depression</strong>: total of 9 assessed (<em>100.0% of all those assessed for MH, 9/9</em>), with 1 positive (<em>11.1% of all those screened for depression, 1/9</em>).</p></li>
<li><p><strong>Anxiety</strong>: total of 8 assessed (<em>88.9% of all those assessed for MH, 8/9</em>), with 0 positive (<em>0.0% of all those screened for anxiety, 0/8</em>).</p></li>
<li><p><strong>PTSD</strong>: total of 1 assessed (<em>11.1% of all those assessed for MH, 1/9</em>), with 1 positive (<em>100.0% of all those screened for PTSD, 1/1</em>).</p></li>
</ul>
<p><br></p>
<div class="cell">
<div class="cell-output-display">

<table data-quarto-disable-processing="true" class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto; font-size: 10px; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Date </th>
   <th style="text-align:center;"> MH Assessed </th>
   <th style="text-align:center;"> Depression Assessed </th>
   <th style="text-align:center;"> % Depression Assessed </th>
   <th style="text-align:center;"> Depression positive </th>
   <th style="text-align:center;"> % Depression positive </th>
   <th style="text-align:center;"> Anxiety Assessed </th>
   <th style="text-align:center;"> % Anxiety Assessed </th>
   <th style="text-align:center;"> Anxiety positive </th>
   <th style="text-align:center;"> % Anxiety positive </th>
   <th style="text-align:center;"> PTSD Assessed </th>
   <th style="text-align:center;"> % PTSD Assessed </th>
   <th style="text-align:center;"> PTSD positive </th>
   <th style="text-align:center;"> % PTSD positive </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 01/2023 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 02/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 03/2023 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 33.3% </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 33.3% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 33.3% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 100.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 04/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 05/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 06/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 07/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 08/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 09/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10/2023 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 66.7% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 11/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 12/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 01/2024 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 02/2024 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 03/2024 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 04/2024 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;background-color: lightgrey !important;"> Totals </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 9 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 9 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 100.0% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 1 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 11.1% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 8 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 88.9% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 0 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 0.0% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 1 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 11.1% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 1 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 100.0% </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><br> <br></p>
</section>
<section id="pre-exposure-prophylaxis-prep" class="level3">
<h3 data-anchor-id="pre-exposure-prophylaxis-prep">Pre-Exposure Prophylaxis (PrEP)</h3>
<p>PrEP eligibility is covered by several different questions scattered within the assessment that determine whether an individual may be at risk for contracting HIV and could benefit from a PrEP assessment. The total number of assessments Neria conducted where the individual answered at least one of the questions regarding their risk of contracting HIV, and therefore their potential need for PrEP, was <strong>79 assessments</strong> (<em>98.8% of all those assessed, 79/80</em>). The total number of assessments where the individual was considered at risk and therefore eligible for PrEP was <strong>71 assessments</strong> (<em>89.9% of all those assessed for their HIV risk, 71/79</em>). Once an individual is determined to be eligible for PrEP based on their risks for contracting HIV, our staff is then instructed to discuss the individual’s knowledge of PrEP and several other factors, providing education and a referral for PrEP initiation and linkage to a provider. The PrEP assessment is defined as being conducted as long as at least one of the questions within this individualized assessment is answered. The total number of assessments where the individual was eligible for PrEP based on their risks <em>and</em> received this PrEP assessment was <strong>32 assessments</strong> (<em>45.1% of all those eligible for PrEP, 32/71</em>).</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">

<table data-quarto-disable-processing="true" class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto; font-size: 11px; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Date </th>
   <th style="text-align:center;"> Assessed </th>
   <th style="text-align:center;"> Risk Assessed </th>
   <th style="text-align:center;"> % At Risk </th>
   <th style="text-align:center;"> PrEP Eligible </th>
   <th style="text-align:center;"> % Eligible </th>
   <th style="text-align:center;"> PrEP Assessed </th>
   <th style="text-align:center;"> % Assessed </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 01/2023 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 62.5% </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 80.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 02/2023 </td>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 70.0% </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 57.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 03/2023 </td>
   <td style="text-align:center;"> 19 </td>
   <td style="text-align:center;"> 19 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 14 </td>
   <td style="text-align:center;"> 73.7% </td>
   <td style="text-align:center;"> 11 </td>
   <td style="text-align:center;"> 78.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 04/2023 </td>
   <td style="text-align:center;"> 17 </td>
   <td style="text-align:center;"> 17 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 9 </td>
   <td style="text-align:center;"> 52.9% </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 77.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 05/2023 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 166.7% </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 40.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 06/2023 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 50.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 07/2023 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 08/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> Inf </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 09/2023 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 66.7% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 50.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10/2023 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 40.0% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 50.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 11/2023 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 37.5% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 12/2023 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> Inf </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 01/2024 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 300.0% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 33.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 02/2024 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> Inf </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 03/2024 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 300.0% </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 04/2024 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 100.0% </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 100.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;background-color: lightgrey !important;"> Totals </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 80 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 79 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 98.8% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 71 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 89.9% </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 32 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 45.1% </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><br></p>
<p>An individual is considered at risk for contracting HIV and eligible for PrEP based on whether they meet at least one of the criteria listed below. However, according to the Ohio Department of Health (ODH), anyone who is negative for HIV is considered eligible for PrEP.</p>
<ul>
<li><p><strong>Exchange of money/drugs for sex within their lifetime</strong></p></li>
<li><p><strong>More than 3 sexual partners within the past year</strong></p></li>
<li><p><strong>Shared works (IDU) within their lifetime</strong></p></li>
<li><p><strong>Diagnosed with a sexually transmitted infection (STI) within the past year</strong></p></li>
<li><p><strong>Identifies as a MSM and endorsed unprotected anal sex, a diagnosis of syphilis/gonorrhea, or sex with a PLWHA within the past year</strong></p></li>
<li><p><strong>Identifies as a heterosexual female and endorsed unprotected vaginal/anal sex within the past year with a partner who is either a MSM, an IDU, or a PLWHA</strong></p></li>
</ul>
<p><br></p>
</section>
</section>
<section id="hiv-testing" class="level2">
<h2 data-anchor-id="hiv-testing">HIV Testing</h2>
<p>The total number of HIV tests, including both CTR and EHE tests, are shown in the plot below. These only include rapid-based HIV tests that are performed by Neria, and does not include any lab tests that are initiated by medical staff prompted by EIP, or lab draws performed in the community (<em>unless it is the result of an initial rapid test</em>). The plot has the ability to select only CTR/EHE tests, and has the ability to zoom in on particular time frames by clicking and dragging. You can reset the graph by double-clicking within the plot.</p>
<p><br> <br></p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-b875de5984e8534c7d5f" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-b875de5984e8534c7d5f">{"x":{"visdat":{"3cec156f537a":["function () ","plotlyVisDat"]},"cur_data":"3cec156f537a","attrs":{"3cec156f537a":{"x":{},"y":{},"text":{},"textposition":"auto","marker":{"color":"lightskyblue"},"name":"CTR Tests","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"},"3cec156f537a.1":{"x":{},"y":{},"text":{},"textposition":"auto","marker":{"color":"darkgreen"},"name":"EHE Tests","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Brempong Monthly Rapid HIV Testing","yaxis":{"domain":[0,1],"automargin":true,"title":"Total HIV Tests"},"barmode":"stack","xaxis":{"domain":[0,1],"automargin":true,"title":"Date"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false,"displayModeBar":false},"data":[{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[0,0,0,0,1,1,1,0,1,2,7,0,1,0,1,0],"text":[0,0,0,0,1,1,1,0,1,2,7,0,1,0,1,0],"textposition":["auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto"],"marker":{"color":"lightskyblue","line":{"color":"rgba(31,119,180,1)"}},"name":"CTR Tests","type":"bar","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01","2024-01-01","2024-02-01","2024-03-01","2024-04-01"],"y":[7,10,15,15,1,0,0,0,0,0,1,0,0,0,0,0],"text":[7,10,15,15,1,0,0,0,0,0,1,0,0,0,0,0],"textposition":["auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto","auto"],"marker":{"color":"darkgreen","line":{"color":"rgba(255,127,14,1)"}},"name":"EHE Tests","type":"bar","error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<p>Out of the total number of HIV tests that Neria has conducted (<strong>n = 64</strong>), there have been <span style="color: red;"><strong>0 positive tests</strong></span> (<em>0.00% of all HIV tests, 0/64</em>). There have been a total of 0 positive CTR tests (<em>0.00% of all CTR tests, 0/15</em>) and a total of 0 positive EHE tests (<em>0.00% of all EHE tests, 0/49</em>).</p>
<p>For the individuals positively identified through testing, Neria has identified a total of <span style="color: red;"><strong>0 new positive individuals</strong></span> (<em>0.0% of all positive HIV tests, 0/0</em>). This number is comprised of 0 new positives from CTR testing (<em>0.0% percent of all CTR positive tests, 0/0</em>) and 0 new positives from EHE testing (<em>0.0% percent of all EHE positive tests, 0/0</em>). Therefore, the overall positivity rate for Neria’s HIV testing is <span style="color: red;"><strong>0.00%</strong></span> (<em>0/64</em>), and for each program specifically is as follows: 0.00% for CTR (<em>0/15</em>) and 0.00% for EHE (<em>0/49</em>).</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">

<table data-quarto-disable-processing="true" class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto; font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;">  </th>
   <th style="text-align:center;"> Total </th>
   <th style="text-align:center;"> CTR </th>
   <th style="text-align:center;"> EHE </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> Number of Tests </td>
   <td style="text-align:center;"> 64 </td>
   <td style="text-align:center;"> 15 </td>
   <td style="text-align:center;"> 49 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Positives </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> New Positives </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Positivity Rate </td>
   <td style="text-align:center;"> 0.00% </td>
   <td style="text-align:center;"> 0.00% </td>
   <td style="text-align:center;"> 0.00% </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><br> <br></p>
<p>Additionally, false positive tests occur when the individual has an initial reactive/positive test, but additional testing shows that their final status is actually a negative result. Neria has had a total of <strong>0 tests that have resulted in a false positive</strong> (<em>0.0% of all HIV tests, 0/64</em>), or those that had an initial reactive result but a final negative status.</p>
<p>There are also instances when the initial test may be reactive, but the confirmatory test is negative, leading to a discordant result that requires additional testing (<em>HIV RNA testing</em>). Until that RNA testing is completed, this is known as an Indeterminate result. Neria currently has a total of <strong>0 tests that are indeterminate and in need of RNA testing</strong> (<em>0.0% of all HIV tests, 0/64</em>). This is counted when the final test status is noted as Indeterminate. When the RNA testing confirms the final result, the final status is updated. Therefore, this only counts those that are currently marked as Indeterminate and have not had the follow-up RNA testing necessary to know the individual’s final HIV status.</p>
</section>
<section id="hepatitis-c-testing" class="level2">
<h2 data-anchor-id="hepatitis-c-testing">Hepatitis C Testing</h2>
<p>The total number of Hepatitis C rapid tests conducted by Neria per month are shown in the plot below. This only considers the rapid tests initiated by our staff, not lab-initiated tests or blood draws (<em>unless it is the result of an initial rapid test</em>). The plot has the ability to zoom in on particular time frames by clicking and dragging. You can reset the graph by double-clicking within the plot.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-b2d5661a8f0bf9cf3fb8" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-b2d5661a8f0bf9cf3fb8">{"x":{"visdat":{"3cec72c85822":["function () ","plotlyVisDat"]},"cur_data":"3cec72c85822","attrs":{"3cec72c85822":{"x":{},"y":{},"text":{},"textposition":"auto","marker":{"color":"gold"},"name":"HCV Tests","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Brempong Monthly Hepatitis C Testing","yaxis":{"domain":[0,1],"automargin":true,"title":"Total HCV Tests","dtick":1,"rangemode":"tozero","range":[0,14]},"xaxis":{"domain":[0,1],"automargin":true,"title":"Date"},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false,"displayModeBar":false},"data":[{"x":["2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-09-01","2023-11-01","2024-03-01"],"y":[4,12,13,1,1,2,8,1],"text":[4,12,13,1,1,2,8,1],"textposition":["auto","auto","auto","auto","auto","auto","auto","auto"],"marker":{"color":"gold","line":{"color":"rgba(31,119,180,1)"}},"name":"HCV Tests","type":"bar","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p><br> <br></p>
<p>Out of the total number of rapid HCV tests conducted by Neria (<strong>n = 42</strong>), there were a total of <span style="color: orange;"><strong>8 reactive/positive HCV results</strong></span> (<em>19.0% of all rapid HCV tests, 8/42</em>). The total number of newly-identified positives from these tests was <strong>3 new HCV positive individuals</strong> (<em>37.5% of all HCV positive HCV tests, 3/8</em>). Therefore, the overall positivity rate for Neria’s Hepatitis C testing is <span style="color: orange;"><strong>7.14%</strong></span> (<em>3/42</em>).</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">

<table data-quarto-disable-processing="true" class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto; font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;">  </th>
   <th style="text-align:center;"> Total </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> Number of Tests </td>
   <td style="text-align:center;"> 42 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Positives </td>
   <td style="text-align:center;"> 8 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> New Positives </td>
   <td style="text-align:center;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Positivity Rate </td>
   <td style="text-align:center;"> 7.14% </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><br></p>
</section>
<section id="referrals" class="level2">
<h2 data-anchor-id="referrals">Referrals</h2>
<p>Referral information can be provided to patients/clients regardless of what occurs during their encounter, and regardless of whether or not they received any EIP services during their encounter. They may be provided based on brief conversations with our staff or from information gathered from medical staff that may not have been documented within the EIP database. Referrals are also documented in multiple places within the EIP database, those provided during the encounter and those provided during any linkage follow-up. Even if referrals are provided during the linkage process, they are represented here as any information gathered during the encounter could have led to that referral being provided. The referrals will be noted separately, but also as a combined total, and the referrals provided specifically during the linkage process will be repeated in the linkage to care section.</p>
<div style="width: 50%; float: left;">
<div class="cell">
<div class="cell-output-display">

<table data-quarto-disable-processing="true" class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0; font-size: 10px; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;">  </th>
   <th style="text-align:center;"> Encounter referral </th>
   <th style="text-align:center;"> Linkage referral </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> HIV </td>
   <td style="text-align:center;"> 113 </td>
   <td style="text-align:center;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Hepatitis C </td>
   <td style="text-align:center;"> 87 </td>
   <td style="text-align:center;"> 8 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> SUD </td>
   <td style="text-align:center;"> 99 </td>
   <td style="text-align:center;"> 5 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Human Trafficking </td>
   <td style="text-align:center;"> 84 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Mental Health </td>
   <td style="text-align:center;"> 118 </td>
   <td style="text-align:center;"> 70 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Housing </td>
   <td style="text-align:center;"> 107 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> PrEP </td>
   <td style="text-align:center;"> 92 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> STI </td>
   <td style="text-align:center;"> 107 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Food services </td>
   <td style="text-align:center;"> 112 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Financial assistance </td>
   <td style="text-align:center;"> 105 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Person abuse </td>
   <td style="text-align:center;"> 87 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> General health </td>
   <td style="text-align:center;"> 111 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> PCP* </td>
   <td style="text-align:center;"> 72 </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:right;"> ED SW* </td>
   <td style="text-align:center;"> 11 </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Peer services* </td>
   <td style="text-align:center;"> 27 </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Other </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:right;font-weight: bold;background-color: lightgrey !important;"> Totals </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 1335 </td>
   <td style="text-align:center;font-weight: bold;background-color: lightgrey !important;"> 89 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup>*</sup> No linkage referral documentation</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>Referrals are documented in the EIP database in three different ways at the encounter level: (1) provided information, such as brochures/pamphlets or referral lists with community programs, (2) provided internal referral for that service to one of EIP’s linkage coordinators, or (3) an external referral to a specific agency. Regardless of the nature of the referral, they way a referral is defined here is as long as one of those options are covered for that service.</p>
<p>There are a few referrals that are only documented at the encounter level, and do not have any component for documentation on the linkage referral list. Those referral types are indicated within the table to the left as well as the figure below, and listed here: <em>primary care (PCP), ED social work (SW), and Peer services</em>.</p>
<p>The table to the left highlights the total number of referrals provided during the initial encounter as well as the total number of referrals provided during the linkage follow-up. These referrals do not necessarily mean that Neria is the one who made the referral, since referrals can be made at any point during the encounter/linkage process and by anyone involved. <em>For example, one staff member may be responsible for one portion of the encounter/linkage, and provided referrals, whereas another staff member may be responsible for another part of the encounter/linkage and provided the referral</em>.</p>
<p>The figure below shows the total number of referrals that were provided by each service. This includes any referrals provided during either the initial encounter or the linkage follow-up. The figure is sorted by most total referrals provided to the least. A service referral is only counted once here as long as it was made during either the encounter or linkage process. <em>For example, if an HIV referral was made bother during the encounter and linkage process, it is only counted once for that encounter</em>.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
</section>
<section id="linkage-to-care" class="level2">
<h2 data-anchor-id="linkage-to-care">Linkage to Care</h2>
<p>Linkage to care (LTC) cases can be initiated for any number of reasons, including (<em>but not limited to</em>) self-report of need from the individual, identification of need based on EIP assessment and/or testing information, referral from medical staff outside of EIP, community referrals, or identification and/or referrals based on screening and testing through typical ED/hospital care. Some of our linkage staff are more specialized in specific types of LTC services, while some are cross-trained and can work multiple LTC services. Therefore, this section will cover all aspects of EIP LTC services, so if Neria does not cover some aspects of linkage, that area will still be represented here but will not show any data, or limited data based on the overall encounter and linkage information maintained within the record. This section will first go over the summary of cases worked by Neria, and general numbers of each linkage service and outcome, then will go into greater examination of each type of LTC service.</p>
<p>The total number of LTC cases that Neria has been involved with is <strong>139 LTC cases</strong>. Our linkage staff is trained to open a linkage case any time need is identified, and then we are able to know the outcome of the case based on their documention within that LTC case. This way, we are able to understand the full scope of need for those we encounter, and determine what happens as we try to engage the patient after their ED visit. We use the term “eligible” cases for those that our linkage team are realistically able to follow-up with and at least have some ability to engage with the individual after leaving the ED. Cases that are designated as “ineligible” include the following situations: the patient is already linked to care, they are deceased, they are incarcerated, they decline linkage services, or there is no contact information for which to follow-up. Also, ongoing linkage cases mean that the individual already has a current linkage case open, so rather than working multiple cases or counting the linkage case twice, we exclude these situations due to ongoing linkage already in process. The total number of Neria’s cases that were “eligible” were <strong>117 eligible LTC cases</strong> (<em>84.2% of all LTC cases, 117/139</em>). Neria currently has an open case load of <strong>17 open cases</strong> (<em>14.5% of all eligible LTC cases, 17/117</em>), with <strong>9 open LTC cases</strong> being open longer than 90 days (<em>52.9% of all open LTC cases, 9/17</em>). Therefore, Neria has successfully <strong>closed 105 LTC cases</strong> (<em>89.7% of all eligible LTC cases, 105/117</em>), with a total of <strong>56 cases successfully linked to care</strong> for their particular service (<em>53.3% of all closed LTC cases, 56/105</em>). A summary table of these total LTC numbers are shown below. For each particular type of LTC service, you can review each tab below the table.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">

<table data-quarto-disable-processing="true" class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto; font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;">  </th>
   <th style="text-align:center;"> Total </th>
   <th style="text-align:center;"> % </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> Total Cases </td>
   <td style="text-align:center;"> 139 </td>
   <td style="text-align:center;">  </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Eligible Cases </td>
   <td style="text-align:center;"> 117 </td>
   <td style="text-align:center;"> 84.2% </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Open Cases </td>
   <td style="text-align:center;"> 17 </td>
   <td style="text-align:center;"> 14.5% </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Open &gt;90 days </td>
   <td style="text-align:center;"> 9 </td>
   <td style="text-align:center;"> 52.9% </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Closed Cases </td>
   <td style="text-align:center;"> 105 </td>
   <td style="text-align:center;"> 89.7% </td>
  </tr>
  <tr>
   <td style="text-align:right;"> Linked </td>
   <td style="text-align:center;"> 56 </td>
   <td style="text-align:center;"> 53.3% </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><br></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">HIV</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">HCV</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false">SUD</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false">Human Trafficking</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-5" role="tab" aria-controls="tabset-2-5" aria-selected="false">Mental Health</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-6" role="tab" aria-controls="tabset-2-6" aria-selected="false">Housing</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-7-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-7" role="tab" aria-controls="tabset-2-7" aria-selected="false">PrEP</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-8-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-8" role="tab" aria-controls="tabset-2-8" aria-selected="false">Additional services</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p>HIV linkage cases are further stratified by those that are cases worked for individuals newly diagnosed versus those that were diagnosed previously. The HIV Linkage Flow Diagram is provided here for Neria’s HIV linkage cases.</p>
<p>Neria has worked on a total of <strong>7 HIV linkage cases</strong> (<em>5.0% of all linkage cases, 7/139</em>). Out of all HIV linkage cases, there were a total of 2 for those newly diagnosed with HIV (<em>28.6% of all HIV linkage cases, 2/7</em>), and a total of 5 for those that have been previously diagnosed (<em>71.4% of all HIV linkage cases, 5/7</em>).</p>
<p>A total of 4 of these cases are “eligible” to be linked to care (<em>57.1% of all HIV linkage cases, 4/7</em>), and the reasons the remaining 3 were “ineligible” are noted in the flow diagram.</p>
<p>Out of those “eligible” to be linked, 2 were for those newly diagnosed for HIV (<em>50.0% of all “eligible” HIV linkage cases, 2/4</em>), and 2 were for those previously diagnosed (<em>50.0% of all “eligible” HIV linkage cases, 2/4</em>). Neria is currently working on 0 of these HIV linkage cases (<em>0.0% of which have been open for more than 90 days</em>), and therefore has closed a total of 4 thus far (<em>100.0% of all “eligible” HIV linkage cases, 4/4</em>). Out of those cases closed, a total of 1 were unable to be linked to care (<em>25.0% of all closed HIV linkage cases, 1/4</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;HIV Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 3 HIV linkage cases</strong> (<em>75.0% of all closed HIV linkage cases, 3/4</em>). Out of all those cases that were successfully linked to care, 2 were for those newly diagnosed with HIV (<em>100.0% of all “eligible” HIV linkage cases for newly diagnosed individuals, 2/2</em>), and 1 were for those that were previously diagnosed (<em>50.0% of all “eligible” HIV linkage cases for previously diagnosed individuals, 1/2</em>).</p>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>Hepatitis C linkage cases are further stratified by those that are cases worked for individuals newly diagnosed versus those that were diagnosed previously. The HCV Linkage Flow Diagram is provided here for Neria’s HCV linkage cases.</p>
<p>Neria has worked on a total of <strong>14 HCV linkage cases</strong> (<em>10.1% of all linkage cases, 14/139</em>). Out of all HCV linkage cases, there were a total of 8 for those newly diagnosed with HCV (<em>57.1% of all HCV linkage cases, 8/14</em>), and a total of 5 for those that have been previously diagnosed (<em>35.7% of all HCV linkage cases, 5/14</em>).</p>
<p>A total of 12 of these cases are “eligible” to be linked to care (<em>85.7% of all HCV linkage cases, 12/14</em>), and the reasons the remaining 2 were “ineligible” are noted in the flow diagram.</p>
<p>Out of those “eligible” to be linked, 7 were for those newly diagnosed for HCV (<em>58.3% of all “eligible” HCV linkage cases, 7/12</em>), and 4 were for those previously diagnosed (<em>33.3% of all “eligible” HCV linkage cases, 4/12</em>). Neria is currently working on 3 of these HCV linkage cases (<em>66.7% of which have been open for more than 90 days</em>), and therefore has closed a total of 9 thus far (<em>75.0% of all “eligible” HCV linkage cases, 9/12</em>). Out of those cases closed, a total of 5 were unable to be linked to care (<em>55.6% of all closed HCV linkage cases, 5/9</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;HCV Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 4 HCV linkage cases</strong> (<em>44.4% of all closed HCV linkage cases, 4/9</em>). Out of all those cases that were successfully linked to care, 3 were for those newly diagnosed with HCV (<em>42.9% of all “eligible” HCV linkage cases for newly diagnosed individuals, 3/7</em>), and 1 were for those that were previously diagnosed (<em>25.0% of all “eligible” HCV linkage cases for previously diagnosed individuals, 1/4</em>).</p>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<p>The SUD Linkage Flow Diagram is provided here for Neria’s SUD linkage cases.</p>
<p>Neria has worked on a total of <strong>10 SUD linkage cases</strong> (<em>7.2% of all linkage cases, 10/139</em>).</p>
<p>A total of 8 of these cases are “eligible” to be linked to care (<em>80.0% of all SUD linkage cases, 8/10</em>), and the reasons the remaining 2 were “ineligible” are noted in the flow diagram.</p>
<p>Neria is currently working on 3 of these SUD linkage cases (<em>66.7% of which have been open for more than 90 days</em>), and therefore has closed a total of 5 thus far (<em>62.5% of all “eligible” SUD linkage cases, 5/8</em>). Out of those cases closed, a total of 1 were unable to be linked to care (<em>20.0% of all closed SUD linkage cases, 1/5</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;SUD Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 4 SUD linkage cases</strong> (<em>80.0% of all closed SUD linkage cases, 4/5</em>).</p>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<p>The Human Trafficking (HT) Linkage Flow Diagram is provided here for Neria’s HT linkage cases.</p>
<p>Neria has worked on a total of <strong>0 HT linkage cases</strong> (<em>0.0% of all linkage cases, 0/139</em>).</p>
<p>A total of 0 of these cases are “eligible” to be linked to care (<em>0.0% of all HT linkage cases, 0/0</em>), and the reasons the remaining 0 were “ineligible” are noted in the flow diagram.</p>
<p>Neria is currently working on 0 of these HT linkage cases (<em>0.0% of which have been open for more than 90 days</em>), and therefore has closed a total of 0 thus far (<em>0.0% of all “eligible” HT linkage cases, 0/0</em>). Out of those cases closed, a total of 0 were unable to be linked to care (<em>0.0% of all closed HT linkage cases, 0/0</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;HT Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 0 HT linkage cases</strong> (<em>0.0% of all closed HT linkage cases, 0/0</em>).</p>
</div>
<div id="tabset-2-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-5-tab">
<p>The Mental Health (MH) Linkage Flow Diagram is provided here for Neria’s MH linkage cases.</p>
<p>Neria has worked on a total of <strong>132 MH linkage cases</strong> (<em>95.0% of all linkage cases, 132/139</em>).</p>
<p>A total of 109 of these cases are “eligible” to be linked to care (<em>82.6% of all MH linkage cases, 109/132</em>), and the reasons the remaining 23 were “ineligible” are noted in the flow diagram.</p>
<p>Neria is currently working on 11 of these MH linkage cases (<em>45.5% of which have been open for more than 90 days</em>), and therefore has closed a total of 98 thus far (<em>89.9% of all “eligible” MH linkage cases, 98/109</em>). Out of those cases closed, a total of 51 were unable to be linked to care (<em>52.0% of all closed MH linkage cases, 51/98</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;MH Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 47 MH linkage cases</strong> (<em>48.0% of all closed MH linkage cases, 47/98</em>).</p>
</div>
<div id="tabset-2-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-6-tab">
<p>The Housing Linkage Flow Diagram is provided here for Neria’s Housing linkage cases.</p>
<p>Neria has worked on a total of <strong>1 Housing linkage cases</strong> (<em>0.7% of all linkage cases, 1/139</em>).</p>
<p>A total of 1 of these cases are “eligible” to be linked to care (<em>100.0% of all Housing linkage cases, 1/1</em>), and the reasons the remaining 0 were “ineligible” are noted in the flow diagram.</p>
<p>Neria is currently working on 1 of these Housing linkage cases (<em>100.0% of which have been open for more than 90 days</em>), and therefore has closed a total of 0 thus far (<em>0.0% of all “eligible” Housing linkage cases, 0/1</em>). Out of those cases closed, a total of 0 were unable to be linked to care (<em>0.0% of all closed Housing linkage cases, 0/0</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;Housing Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 0 Housing linkage cases</strong> (<em>0.0% of all closed Housing linkage cases, 0/0</em>).</p>
</div>
<div id="tabset-2-7" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-7-tab">
<p>The PrEP Linkage Flow Diagram is provided here for Neria’s PrEP linkage cases.</p>
<p>Neria has worked on a total of <strong>1 PrEP linkage cases</strong> (<em>0.7% of all linkage cases, 1/139</em>).</p>
<p>A total of 1 of these cases are “eligible” to be linked to care (<em>100.0% of all PrEP linkage cases, 1/1</em>), and the reasons the remaining 0 were “ineligible” are noted in the flow diagram.</p>
<p>Neria is currently working on 0 of these PrEP linkage cases (<em>0.0% of which have been open for more than 90 days</em>), and therefore has closed a total of 1 thus far (<em>100.0% of all “eligible” PrEP linkage cases, 1/1</em>). Out of those cases closed, a total of 0 were unable to be linked to care (<em>0.0% of all closed PrEP linkage cases, 0/1</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;PrEP Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 1 PrEP linkage cases</strong> (<em>100.0% of all closed PrEP linkage cases, 1/1</em>).</p>
</div>
<div id="tabset-2-8" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-8-tab">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">STI</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Food services</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Financial assistance</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">Person abuse</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false">General health</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-6" role="tab" aria-controls="tabset-1-6" aria-selected="false">Other Linkage</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>The STI Linkage Flow Diagram is provided here for Neria’s STI linkage cases.</p>
<p>Neria has worked on a total of <strong>0 STI linkage cases</strong> (<em>0.0% of all linkage cases, 0/139</em>).</p>
<p>A total of 0 of these cases are “eligible” to be linked to care (<em>0.0% of all STI linkage cases, 0/0</em>), and the reasons the remaining 0 were “ineligible” are noted in the flow diagram.</p>
<p>Neria is currently working on 0 of these STI linkage cases (<em>0.0% of which have been open for more than 90 days</em>), and therefore has closed a total of 0 thus far (<em>0.0% of all “eligible” STI linkage cases, 0/0</em>). Out of those cases closed, a total of 0 were unable to be linked to care (<em>0.0% of all closed STI linkage cases, 0/0</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;STI Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 0 STI linkage cases</strong> (<em>0.0% of all closed STI linkage cases, 0/0</em>).</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>The Food services Linkage Flow Diagram is provided here for Neria’s Food services linkage cases.</p>
<p>Neria has worked on a total of <strong>0 Food services linkage cases</strong> (<em>0.0% of all linkage cases, 0/139</em>).</p>
<p>A total of 0 of these cases are “eligible” to be linked to care (<em>0.0% of all Food services linkage cases, 0/0</em>), and the reasons the remaining 0 were “ineligible” are noted in the flow diagram.</p>
<p>Neria is currently working on 0 of these Food services linkage cases (<em>0.0% of which have been open for more than 90 days</em>), and therefore has closed a total of 0 thus far (<em>0.0% of all “eligible” Food services linkage cases, 0/0</em>). Out of those cases closed, a total of 0 were unable to be linked to care (<em>0.0% of all closed Food services linkage cases, 0/0</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;Food Insecurity Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 0 Food services linkage cases</strong> (<em>0.0% of all closed Food services linkage cases, 0/0</em>).</p>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>The Financial assistance Linkage Flow Diagram is provided here for Neria’s Financial assistance linkage cases.</p>
<p>Neria has worked on a total of <strong>0 Financial assistance linkage cases</strong> (<em>0.0% of all linkage cases, 0/139</em>).</p>
<p>A total of 0 of these cases are “eligible” to be linked to care (<em>0.0% of all Financial assistance linkage cases, 0/0</em>), and the reasons the remaining 0 were “ineligible” are noted in the flow diagram.</p>
<p>Neria is currently working on 0 of these Financial assistance linkage cases (<em>0.0% of which have been open for more than 90 days</em>), and therefore has closed a total of 0 thus far (<em>0.0% of all “eligible” Financial assistance linkage cases, 0/0</em>). Out of those cases closed, a total of 0 were unable to be linked to care (<em>0.0% of all closed Financial assistance linkage cases, 0/0</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;Financial Assistance Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 0 Financial assistance linkage cases</strong> (<em>0.0% of all closed Financial assistance linkage cases, 0/0</em>).</p>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<p>The Person abuse Linkage Flow Diagram is provided here for Neria’s Person abuse linkage cases.</p>
<p>Neria has worked on a total of <strong>0 Person abuse linkage cases</strong> (<em>0.0% of all linkage cases, 0/139</em>).</p>
<p>A total of 0 of these cases are “eligible” to be linked to care (<em>0.0% of all Person abuse linkage cases, 0/0</em>), and the reasons the remaining 0 were “ineligible” are noted in the flow diagram.</p>
<p>Neria is currently working on 0 of these Person abuse linkage cases (<em>0.0% of which have been open for more than 90 days</em>), and therefore has closed a total of 0 thus far (<em>0.0% of all “eligible” Person abuse linkage cases, 0/0</em>). Out of those cases closed, a total of 0 were unable to be linked to care (<em>0.0% of all closed Person abuse linkage cases, 0/0</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;Person Abuse Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 0 Person abuse linkage cases</strong> (<em>0.0% of all closed Person abuse linkage cases, 0/0</em>).</p>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<p>The General health Linkage Flow Diagram is provided here for Neria’s General health linkage cases.</p>
<p>Neria has worked on a total of <strong>1 General health linkage cases</strong> (<em>0.7% of all linkage cases, 1/139</em>).</p>
<p>A total of 1 of these cases are “eligible” to be linked to care (<em>100.0% of all General health linkage cases, 1/1</em>), and the reasons the remaining 0 were “ineligible” are noted in the flow diagram.</p>
<p>Neria is currently working on 0 of these General health linkage cases (<em>0.0% of which have been open for more than 90 days</em>), and therefore has closed a total of 1 thus far (<em>100.0% of all “eligible” General health linkage cases, 1/1</em>). Out of those cases closed, a total of 0 were unable to be linked to care (<em>0.0% of all closed General health linkage cases, 0/1</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;General Health Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 1 General health linkage cases</strong> (<em>100.0% of all closed General health linkage cases, 1/1</em>).</p>
</div>
<div id="tabset-1-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-6-tab">
<p>The Other Linkage Flow Diagram is provided here for Neria’s Other linkage cases.</p>
<p>Neria has worked on a total of <strong>1 Other linkage cases</strong> (<em>0.7% of all linkage cases, 1/139</em>).</p>
<p>A total of 1 of these cases are “eligible” to be linked to care (<em>100.0% of all Other linkage cases, 1/1</em>), and the reasons the remaining 0 were “ineligible” are noted in the flow diagram.</p>
<p>Neria is currently working on 1 of these Other linkage cases (<em>100.0% of which have been open for more than 90 days</em>), and therefore has closed a total of 0 thus far (<em>0.0% of all “eligible” Other linkage cases, 0/1</em>). Out of those cases closed, a total of 0 were unable to be linked to care (<em>0.0% of all closed Other linkage cases, 0/0</em>), with the reasons as to why are shown in the flow diagram. These reasons are not mutually exclusive, and there could be multiple reasons why those linkage cases were unsuccessful.</p>
<div class="cell" data-lightbox="{&quot;description&quot;:&quot;Other Linkage Flow Diagram&quot;}">
<div class="cell-output-display">
<p><img src="n_brempong_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Therefore, Neria has <strong>successfully linked a total of 0 Other linkage cases</strong> (<em>0.0% of all closed Other linkage cases, 0/0</em>).</p>
</div>
</div>
</div>
</div>
</div>
</div>



</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>